name = "my-mvp"
compatibility_date = "2025-02-24"

pages_build_output_dir = "out"

#[site]
# Optional: If you have static assets in a public directory
# bucket = "./public"

[build]
node_version = "22"
