name = "my-mvp"
compatibility_date = "2025-02-23"

pages_build_output_dir = "out"

# Proxy rules to route /api/vote requests to the external voting-app Worker
[[pages.routes]]
pattern = "/api/vote*"
custom_domain = "voting-app.hackerinverse.workers.dev"